version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Hotel@12345
      MYSQL_DATABASE: dg_hotel
      MYSQL_USER: demo
      MYSQL_PASSWORD: Hotel@12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
